---
config:
    theme: redux
---
flowchart TD
    Start(["Start"])
    Splash["Welcome"]
    Onboarding["Onboarding"]
    OnboardingChoice{"Sign-up / Sign-in"}
    SignUp[["Sign-Up"]]
    SignIn[["Sign-In"]]
    StartMenu["Start Menu"]
    StartMenuChoice{"New Game / Load Game"}
    SelectAdventure["Select Adventure"]
    CreateCharacter["Create Character"]
    GameLoop["Play Adventure"]
    Quit["Quit"]
    End(["End"])

    Start --> Splash
    Splash --> Onboarding
    Onboarding --> OnboardingChoice
    OnboardingChoice --> SignUp
    OnboardingChoice --> SignIn
    SignUp --> StartMenu
    SignIn --> StartMenu
    StartMenu --> StartMenuChoice
    StartMenuChoice -- New Game ---> SelectAdventure
    StartMenuChoice -- Load Game ---> GameLoop
    SelectAdventure --> CreateCharacter
    CreateCharacter --> GameLoop
    GameLoop --> GameLoop
    GameLoop --> Quit
    Quit --> End
